### ISSUE TITLE
HMSET/HMGET support?

### ISSUE THREAD

**Issue by tigerinus** [redis-developer/spring-batch-redis#39]
Hello,

I came across your project while looking for a Redis ItemReader/ItemWriter for Spring Batch. Your project looks decent.

Just one question - Do you think you'd be able to support HMSET/HMGET in future release? Is it feasible?

Thanks.

**Comment by jruaux** [comment]
Hi, there is a HSET operation already: https://github.com/redis-developer/spring-batch-redis/blob/master/src/main/java/org/springframework/batch/item/redis/support/operation/Hset.java
What do you have in mind for HMGET? Right now you can configure the DataStructure reader to only scan/listen for hashes through the type option.
