### ISSUE TITLE
 Some confusion of mine?

### ISSUE THREAD

**Issue by yaoqiangpersonal** [redis-developer/spring-batch-redis#56]
There are some difficulties in the quick startup, why not make some default configurations to optimize startup? At the same time, why does the constructor of RedisWriter use the StatefulConnection rather than StatefulRedisConnection?

**Comment by jruaux** [comment]
Spring Batch Redis works for both standalone (StatefulRedisConnection) and cluster connections (StatefulRedisClusterConnection) and StatefulConnection is their common parent class.
