### ISSUE TITLE
StreamItemReader should provide options for failure recovery

### ISSUE THREAD

**Issue by ahawtho** [redis-developer/spring-batch-redis#58]
Currently, `StreamItemReader` always uses `StreamOffset.lastConsumed(stream)` as the stream id for XREADGROUP. This corresponds to the special id `>`. However, this means that if there are any pending messages, these messages will be skipped by the reader.

When starting, the `StreamItemReader` should have an option to read the pending messages before reading new messages. This would give the client a way to recover from a failure and either ack any messages that have already been processed, or reprocess messages that it did not have an opportunity to ack before, giving "at least once" behavior.

**Comment by jruaux** [comment]
Great suggestion. I'll add this to the list of enhancements
